// apps/islands/_frontend/src/islands/Counter.react.jsx
import { useState } from 'react';

export default function Counter({ start, framework }) {
  const [count, setCount] = useState(start);
  return (
    <div className="counter">
      <div className="counter-value" key={count}>{count}</div>
      <div className="counter-buttons">
        <button onClick={() => setCount(count - 1)} aria-label="One less">−</button>
        <button onClick={() => setCount(count + 1)} aria-label="One more">+</button>
      </div>
      <p className="counter-note">{framework}: useState</p>
    </div>
  );
}

// apps/islands/_frontend/src/islands/Counter.solid.jsx
import { createSignal } from 'solid-js';

export default function Counter(props) {
  const [count, setCount] = createSignal(props.start);
  return (
    <div class="counter">
      <div class="counter-value">{count()}</div>
      <div class="counter-buttons">
        <button onClick={() => setCount(count() - 1)} aria-label="One less">−</button>
        <button onClick={() => setCount(count() + 1)} aria-label="One more">+</button>
      </div>
      <p class="counter-note">{props.framework}: createSignal</p>
    </div>
  );
}
